# This is a basic workflow to help you get started with Actions

name: CI

# Run workflow on every push
on: push
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Stage 0
      - name: Test upload to SourceForge
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: bin/test-upload

      # Stage 1
      - name: Provision
        run: sudo bin/provision

      # Stage 2
      - name: Cache downloaded ISO file
        id: cache-downloaded-iso
        uses: actions/cache@v3
        with:
          path: iso-downloaded
          key: key-iso-file

      - name: Downloading the Linux ISO
        run: bin/download-iso

      # Stage 3
      - name: Mounting the virtual Linux DVD
        run: sudo bin/mount-iso

      # Stage 4
      - name: Copying the content from the virtual Linux DVD
        run: sudo bin/copy-iso

      # Stage 5
      - name: Mounting the compressed FS file
        run: sudo bin/mount-compressed-fs

      # Stage 6
      - name: Copying the squashfs files
        run: sudo bin/copy-squashfs

      # Stage 7A: chroot mounts
      - name: Mounting directories needed for chroot
        run: sudo bin/chroot-mounts

      # Stage 7B: chroot apt-get update
      - name: Updating the chroot environment
        run: sudo bin/chroot-update

      # Stage 7C: chroot apt-get upgrade
      - name: Upgrading the chroot environment
        run: sudo bin/chroot-upgrade

      # Stage 7D: chroot install of KeePassXC
      - name: Installing KeePassXC in chroot
        run: sudo bin/chroot-keepassxc

      # Stage 7E: chroot unmounting
      - name: Ending the chroot mounts
        run: sudo bin/chroot-unmount

      # Stage 7F: chroot cleanup
      - name: Post-chroot cleanup operations
        run: sudo bin/chroot-cleanup
