name: SquashFS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run the find-strings-in-squashfs.sh script
        run: bash find-strings-in-squashfs.sh
